#!/usr/bin/env python3
"""Compile the official CDC WHO LMS CSV files into an offline browser bundle."""

import csv
import json
import pathlib
import sys

FILES = {
    "weightForAge": ("wfa-boys.csv", "wfa-girls.csv"),
    "lengthForAge": ("lfa-boys.csv", "lfa-girls.csv"),
    "weightForLength": ("wfl-boys.csv", "wfl-girls.csv"),
    "headForAge": ("hca-boys.csv", "hca-girls.csv"),
}


def load(path: pathlib.Path):
    with path.open(encoding="utf-8-sig", newline="") as handle:
        rows = csv.DictReader(handle)
        first = rows.fieldnames[0]
        return [
            [float(row[first]), float(row["L"]), float(row["M"]), float(row["S"])]
            for row in rows
        ]


def main():
    source = pathlib.Path(sys.argv[1])
    output = pathlib.Path(sys.argv[2])
    data = {}
    for metric, (boys, girls) in FILES.items():
        data[metric] = {
            "male": load(source / boys),
            "female": load(source / girls),
        }
    body = json.dumps(data, separators=(",", ":"))
    output.write_text(
        "/* Official CDC-published WHO Child Growth Standards LMS data.\n"
        " * Source: https://www.cdc.gov/growthcharts/who-data-files.htm\n"
        " * Columns per row: [ageMonthsOrLengthCm, L, M, S].\n"
        " * Generated by scripts/build-who-data.py; do not edit manually. */\n"
        f"(typeof window!=='undefined'?window:globalThis).WHO_LMS_DATA={body};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
